//! Undoable operations on the events *inside* one clip.
//!
//! Every edit here works the same way: capture `(track_idx, clip_id,
//! selected_event_ids)` at construction, snapshot the clip's whole event list
//! into `pre_events` on `edit()`, and restore that snapshot on `undo()`. Most
//! are generated by the `clip_events_edit!` macro over [`ClipEventsEditState`];
//! `InsertNotesEdit` and `DragEventsVelocityEdit` are hand-rolled around it
//! where the post-edit selection or target-id set doesn't fit the macro. All
//! return `EditResult::EventsModified` (see [`EditResult`]). `InsertCaptureEdit`
//! is the one that adds notes from outside the clip: a take inserted by `/`.
//! `QuantizeEventsEdit` is the one that also acts with nothing selected.
//! `InsertNotesEdit` (a double-click or `⌘/Ctrl+V`) and `DragNotesEdit` are
//! the piano roll's note edits (`clip/note_edits.rs`). See `050-undo-redo.md`.

use undo::Record;
use uuid::Uuid;

use crate::models::{
    clip::{Clip, NoteDrag, min_max},
    event::{Event, EventType},
};

use super::super::{CaptureInsert, Sequencer};
use super::{EditResult, SequencerEdit};

// ---------------------------------------------------------------------------
// InsertCaptureEdit — hand-rolled around `ClipEventsEditState`: it adds notes
// from the capture buffer rather than acting on the selection (which may be
// empty), and consumes the buffer once.
// ---------------------------------------------------------------------------

/// A live take inserted into an existing clip: `/` with a lead clip, running
/// ([`Sequencer::build_running_capture_insert`]) or stopped
/// ([`Sequencer::build_stopped_capture_insert`]). The notes are worked out at
/// construction; `edit()` adds them and `undo()` restores the clip's events
/// from before. Like [`CommitClipEdit`](super::CommitClipEdit), the first
/// `edit()` clears the capture buffer and no later one does, so a redo can't
/// wipe a take the user has started since, and undo leaves the buffer cleared.
///
/// A commit never changes the event selection: both directions report the
/// selection the clip had when the edit was built, and the inserted notes
/// are not selected.
pub(crate) struct InsertCaptureEdit {
    /// The target clip, its selection, and the pre-insert snapshot.
    state: ClipEventsEditState,
    /// The inserted notes, in the clip's event ticks. Redo adds these same
    /// notes (same ids) again.
    events: Vec<Event>,
    /// `true` until the first `edit()` has cleared the capture buffer.
    consume_capture: bool,
}

impl InsertCaptureEdit {
    /// The running `/` with a lead clip. `None` when nothing would land in
    /// the clip, so nothing enters the record.
    pub(crate) fn from_running_capture(sequencer: &Sequencer) -> Option<Self> {
        Self::consuming(sequencer, sequencer.build_running_capture_insert()?)
    }

    /// The stopped `/` with a lead clip: the detected phrase at the clip
    /// cursor. `None` when nothing would land in the clip.
    pub(crate) fn from_stopped_capture(sequencer: &Sequencer) -> Option<Self> {
        Self::consuming(sequencer, sequencer.build_stopped_capture_insert()?)
    }

    /// An insert of `insert` into its clip, armed to clear the capture
    /// buffer it came from.
    fn consuming(sequencer: &Sequencer, insert: CaptureInsert) -> Option<Self> {
        let selected_event_ids = sequencer
            .clip_on(insert.track_idx, insert.clip_id)?
            .selected_event_ids();
        Some(Self {
            state: ClipEventsEditState {
                track_idx: insert.track_idx,
                clip_id: insert.clip_id,
                selected_event_ids,
                pre_events: None,
            },
            events: insert.events,
            consume_capture: true,
        })
    }

    /// Lowest and highest pitch of the take's notes, `None` without a note.
    fn take_pitch_range(&self) -> Option<(u8, u8)> {
        min_max(
            self.events
                .iter()
                .filter(|event| event.event_type() == Some(EventType::NoteOn))
                .filter_map(Event::note_number),
        )
    }

    /// Snapshots the clip's events, adds the take's notes and re-pairs, and,
    /// once, clears the capture buffer. Reports the take's pitch range
    /// (`EditResult::EventsModified::inserted_take`).
    pub(super) fn edit(&mut self, sequencer: &mut Sequencer) -> EditResult {
        let selected_event_ids = self.state.selected_event_ids.clone();
        let events = &self.events;
        let mut result = self.state.edit_with(sequencer, |clip| {
            for event in events {
                clip.add_event(event.clone());
            }
            clip.sort_events_by_tick();
            clip.calculate_note_lengths();
            selected_event_ids
        });
        // Every time the take lands — the commit and each redo — so the
        // piano roll can bring it into view the same way.
        if let EditResult::EventsModified { inserted_take, .. } = &mut result {
            *inserted_take = self.take_pitch_range();
        }

        if self.consume_capture && !matches!(result, EditResult::NoOp) {
            sequencer.reset_capture();
            self.consume_capture = false;
        }
        result
    }

    /// Restores the clip's events from before the insert.
    pub(super) fn undo(&mut self, sequencer: &mut Sequencer) -> EditResult {
        self.state.undo(sequencer)
    }
}

// ---------------------------------------------------------------------------
// DragEventsVelocityEdit — hand-rolled because it targets an explicit event
// id set that may not be (and must not become) the real selection: the
// ⌘/Ctrl+drag gesture can target a single hovered-but-unselected note. The
// `clip_events_edit!` macro's shared state always force-restores the real
// selection before mutating, which would corrupt that case.
// ---------------------------------------------------------------------------

/// The ⌘/Ctrl+drag velocity gesture. Targets an explicit id set (which may be
/// a single hovered-but-unselected note) and never touches `event_selection`,
/// so the macro's force-restore-selection path can't be used.
pub(crate) struct DragEventsVelocityEdit {
    /// The target clip and its snapshot. Its `selected_event_ids` is passed
    /// through unchanged in `EditResult::EventsModified` — this edit never
    /// touches `Clip::event_selection`, so the real selection (read once at
    /// construction) is exactly what the UI should keep showing.
    state: ClipEventsEditState,
    /// The notes the gesture nudges — not necessarily the selection.
    event_ids: Vec<Uuid>,
    /// Signed velocity delta of each step of the gesture, in order: one per
    /// pointer move, grown by [`absorb`](Self::absorb) as steps merge. Redo
    /// replays them in turn rather than their sum, because each step is
    /// clamped against the velocity range, so a drag past 127 and back
    /// down doesn't net out to the sum.
    nudges: Vec<i32>,
    /// Identifies the drag, so consecutive nudges from one gesture merge into
    /// one undo step.
    drag_id: u64,
}

impl DragEventsVelocityEdit {
    /// Captures the target clip and the explicit `event_ids` the gesture
    /// nudges. `None` if no clip is selected.
    pub(crate) fn from_sequencer(
        sequencer: &Sequencer,
        event_ids: Vec<Uuid>,
        nudge: i32,
        drag_id: u64,
    ) -> Option<Self> {
        Some(Self {
            state: ClipEventsEditState::from_selected_clip(sequencer)?,
            event_ids,
            nudges: vec![nudge],
            drag_id,
        })
    }

    /// Two `DragEventsVelocityEdit`s merge (coalesce into one undo step) iff
    /// they belong to the same drag gesture.
    pub(super) fn same_gesture(&self, other: &Self) -> bool {
        self.drag_id == other.drag_id
    }

    /// Folds a later step of the same gesture into this edit, so redo of the
    /// merged undo step reproduces the whole drag.
    pub(super) fn absorb(&mut self, other: &Self) {
        self.nudges.extend_from_slice(&other.nudges);
    }

    /// Snapshots the clip's events, then applies each nudge step to the
    /// targeted notes' velocity.
    pub(super) fn edit(&mut self, sequencer: &mut Sequencer) -> EditResult {
        let state = &mut self.state;
        let (event_ids, nudges) = (&self.event_ids, &self.nudges);
        let Some(pre_events) = sequencer.edit_clip_events(state.track_idx, state.clip_id, |clip| {
            let pre_events = clip.events().to_vec();
            for &nudge in nudges {
                clip.nudge_events_velocity(event_ids, nudge);
            }
            pre_events
        }) else {
            return EditResult::NoOp;
        };

        state.pre_events = Some(pre_events);
        state.modified(state.selected_event_ids.clone())
    }

    /// Restores the pre-drag event list.
    pub(super) fn undo(&mut self, sequencer: &mut Sequencer) -> EditResult {
        self.state.undo(sequencer)
    }
}

// ---------------------------------------------------------------------------
// InsertNotesEdit / DragNotesEdit — the piano roll's note edits. Hand-rolled:
// the insert's post-selection is the new notes, and the drag carries its
// explicit id set and `NoteDrag`, which the macro's fields can't express.
// ---------------------------------------------------------------------------

/// Notes into the selected clip ([`Clip::insert_notes`], which trims
/// same-pitch overlaps): a double-click on empty piano-roll grid
/// ([`from_sequencer`](Self::from_sequencer), one note), `⌘/Ctrl+V` in the
/// clip view ([`from_clipboard`](Self::from_clipboard), the note clipboard)
/// or `⌘/Ctrl+D` ([`duplicating_selection`](Self::duplicating_selection)).
/// The notes are built at construction, so redo re-adds the same ids. The
/// new notes become the selection; undo reports the selection from before.
pub(crate) struct InsertNotesEdit {
    /// The target clip, its pre-edit selection, and the snapshot.
    state: ClipEventsEditState,
    /// The new notes as `(note_on, note_off)`.
    notes: Vec<(Event, Event)>,
}

impl InsertNotesEdit {
    /// A note at event tick `tick` and `pitch`, `length` ticks long, at
    /// `velocity`, clamped into the clip ([`Clip::new_note`]). `None` if no
    /// clip is selected.
    pub(crate) fn from_sequencer(
        sequencer: &Sequencer,
        tick: i32,
        length: i32,
        pitch: i32,
        velocity: i32,
    ) -> Option<Self> {
        let note = sequencer
            .selected_clip()?
            .new_note(tick, length, pitch, velocity);
        Self::with_notes(sequencer, vec![note])
    }

    /// The note clipboard with its earliest note at the clip cursor and the
    /// rest keeping their spacing ([`Clip::pasted_notes`] — notes landing
    /// outside the window are dropped, ends stop at the window end). `None`
    /// if no clip is selected or no copied note lands inside the window.
    pub(crate) fn from_clipboard(sequencer: &Sequencer) -> Option<Self> {
        let clip = sequencer.selected_clip()?;
        let notes = clip.pasted_notes(clip.cursor_tick(), sequencer.note_clipboard());
        Self::with_notes(sequencer, notes)
    }

    /// `⌘/Ctrl+D`: copies of the selected notes flush after the selection
    /// ([`Clip::duplicated_notes`]). `None` with nothing selected or no copy
    /// landing inside the window.
    pub(crate) fn duplicating_selection(sequencer: &Sequencer) -> Option<Self> {
        let notes = sequencer.selected_clip()?.duplicated_notes();
        Self::with_notes(sequencer, notes)
    }

    /// `notes` into the selected clip, `None` if there are none.
    fn with_notes(sequencer: &Sequencer, notes: Vec<(Event, Event)>) -> Option<Self> {
        if notes.is_empty() {
            return None;
        }
        Some(Self {
            state: ClipEventsEditState::from_selected_clip(sequencer)?,
            notes,
        })
    }

    /// Snapshots the clip's events and inserts the notes, which become the
    /// selection.
    pub(super) fn edit(&mut self, sequencer: &mut Sequencer) -> EditResult {
        let notes = &self.notes;
        self.state.edit_with(sequencer, |clip| {
            clip.insert_notes(notes.iter().cloned());
            notes.iter().map(|(note_on, _)| note_on.id()).collect()
        })
    }

    /// Restores the clip's events from before the insert.
    pub(super) fn undo(&mut self, sequencer: &mut Sequencer) -> EditResult {
        self.state.undo(sequencer)
    }
}

/// A note drag in the piano roll, applied live: one [`NoteDrag`] (move, or
/// resize from either edge) applied to `event_ids`
/// ([`Clip::apply_note_drag`]). The view sends one step per pointer move, each
/// carrying the whole drag so far from the press, and all the steps of one
/// gesture (`drag_id`) merge into a single undo step. A later step is built
/// holding the gesture's snapshot — the events from before the gesture — as
/// its own, and applies its drag to a copy of those, in one clip edit: so a
/// note dragged across a same-pitch note trims it only where it lands, a note
/// sounding under a running playhead is released or held exactly as for one
/// edit ([`Sequencer::edit_clip_events`]), and a step that doesn't merge
/// (the record was just saved) still undoes to before the gesture. A step
/// back to no change annuls the gesture's undo step. It targets explicit ids
/// and keeps the event selection it was built with.
pub(crate) struct DragNotesEdit {
    /// The target clip, its selection (reported unchanged), and the snapshot
    /// — for a later step, the gesture's, from construction.
    state: ClipEventsEditState,
    /// The dragged notes' `NoteOn` ids.
    event_ids: Vec<Uuid>,
    /// The whole drag so far, from the press.
    drag: NoteDrag,
    /// Identifies the gesture, so its steps merge into one undo step.
    drag_id: u64,
}

impl DragNotesEdit {
    /// `drag` applied to `event_ids` in the selected clip, as a step of
    /// gesture `drag_id`: a later step when the edit on top of `record` is
    /// this gesture's. `None` with no clip selected or no ids, or for a first
    /// step that changes nothing.
    pub(crate) fn from_sequencer(
        sequencer: &Sequencer,
        record: &Record<SequencerEdit>,
        event_ids: Vec<Uuid>,
        drag: NoteDrag,
        drag_id: u64,
    ) -> Option<Self> {
        let previous = record
            .head()
            .checked_sub(1)
            .and_then(|idx| record.get_entry(idx))
            .and_then(|entry| match entry.as_ref() {
                SequencerEdit::DragNotes(edit) if edit.drag_id == drag_id => Some(edit),
                _ => None,
            });
        if event_ids.is_empty() || (previous.is_none() && drag.is_noop()) {
            return None;
        }
        let mut state = ClipEventsEditState::from_selected_clip(sequencer)?;
        state.pre_events = previous.and_then(|previous| previous.state.pre_events.clone());
        Some(Self {
            state,
            event_ids,
            drag,
            drag_id,
        })
    }

    /// Whether `other` is a later step of this gesture.
    pub(super) fn same_gesture(&self, other: &Self) -> bool {
        self.drag_id == other.drag_id
    }

    /// Takes a later step's drag, which already holds the whole gesture.
    pub(super) fn absorb(&mut self, other: &Self) {
        self.drag = other.drag;
    }

    /// Whether this step leaves the notes where the gesture found them.
    pub(super) fn is_noop(&self) -> bool {
        self.drag.is_noop()
    }

    /// Applies the drag: to a copy of the snapshot the step was built with
    /// (a later step), else to the clip's events, snapshotting them first.
    pub(super) fn edit(&mut self, sequencer: &mut Sequencer) -> EditResult {
        let state = &mut self.state;
        let (event_ids, drag, held) = (&self.event_ids, self.drag, state.pre_events.take());
        let selection = &state.selected_event_ids;
        let Some(pre_events) = sequencer.edit_clip_events(state.track_idx, state.clip_id, |clip| {
            let pre_events = match held {
                Some(origin) => {
                    clip.restore_events(origin.clone());
                    origin
                }
                None => clip.events().to_vec(),
            };
            clip.restore_event_selection(selection);
            clip.apply_note_drag(event_ids, drag);
            pre_events
        }) else {
            return EditResult::NoOp;
        };

        state.pre_events = Some(pre_events);
        state.modified(state.selected_event_ids.clone())
    }

    /// Restores the clip's events from before the drag.
    pub(super) fn undo(&mut self, sequencer: &mut Sequencer) -> EditResult {
        self.state.undo(sequencer)
    }
}

// ---------------------------------------------------------------------------
// Event editing — shared state + macro-generated edit structs
// ---------------------------------------------------------------------------

/// The capture/snapshot/restore state every macro-generated event edit shares.
struct ClipEventsEditState {
    /// Track the target clip is on.
    track_idx: usize,
    /// The target clip.
    clip_id: Uuid,
    /// Event selection to restore before mutating and report afterwards.
    selected_event_ids: Vec<Uuid>,
    /// The clip's event list before `edit()`, for `undo()`.
    pre_events: Option<Vec<Event>>,
}

impl ClipEventsEditState {
    /// Captures the target clip and selection, or `None` if nothing is
    /// selected.
    fn from_sequencer(sequencer: &Sequencer) -> Option<Self> {
        Self::from_selected_clip(sequencer).filter(|state| !state.selected_event_ids.is_empty())
    }

    /// Captures the selected clip and its event selection (which may be
    /// empty), or `None` if no clip is selected.
    fn from_selected_clip(sequencer: &Sequencer) -> Option<Self> {
        Some(Self {
            track_idx: sequencer.selected_track_index()?,
            clip_id: sequencer.selected_clip_id()?,
            selected_event_ids: sequencer.selected_clip()?.selected_event_ids(),
            pre_events: None,
        })
    }

    /// `EventsModified` for this clip, reporting `selected_event_ids` as the
    /// post-edit selection.
    fn modified(&self, selected_event_ids: Vec<Uuid>) -> EditResult {
        EditResult::EventsModified {
            track_idx: self.track_idx,
            clip_id: self.clip_id,
            selected_event_ids,
            inserted_take: None,
        }
    }

    /// Snapshots the clip's events, restores the captured selection, runs
    /// `mutate_clip`, and returns `EventsModified` reporting the ids it
    /// returns as the post-edit selection. Goes through
    /// [`Sequencer::edit_clip_events`], so a note the edit moves out from
    /// under a running playhead is released.
    fn edit_with(
        &mut self,
        sequencer: &mut Sequencer,
        mutate_clip: impl FnOnce(&mut Clip) -> Vec<Uuid>,
    ) -> EditResult {
        let selection = &self.selected_event_ids;
        let Some((pre_events, selected_event_ids)) =
            sequencer.edit_clip_events(self.track_idx, self.clip_id, |clip| {
                let pre_events = clip.events().to_vec();
                clip.restore_event_selection(selection);
                (pre_events, mutate_clip(clip))
            })
        else {
            return EditResult::NoOp;
        };

        self.pre_events = Some(pre_events);
        self.modified(selected_event_ids)
    }

    /// Restores the snapshotted event list, releasing like
    /// [`edit_with`](Self::edit_with). The snapshot is moved into the clip
    /// rather than copied: every `edit()` takes a fresh one first.
    fn undo(&mut self, sequencer: &mut Sequencer) -> EditResult {
        let Some(pre_events) = self.pre_events.take() else {
            return EditResult::NoOp;
        };
        let Some(()) = sequencer.edit_clip_events(self.track_idx, self.clip_id, |clip| {
            clip.restore_events(pre_events)
        }) else {
            return EditResult::NoOp;
        };

        self.modified(self.selected_event_ids.clone())
    }
}

/// Generates a pub(crate) struct wrapping `ClipEventsEditState` with optional
/// extra fields, a `from_sequencer` constructor, and `edit`/`undo` methods.
///
/// `post_selection` determines which event IDs are passed as selected after
/// the edit: `keep` preserves pre-edit selection, `clear` passes an empty vec.
///
/// `constructor` optionally names the [`ClipEventsEditState`] constructor:
/// `from_sequencer` (the default) refuses an empty selection,
/// `from_selected_clip` accepts one.
///
/// `mutate` is the closure body applied to the clip during `edit()`.
macro_rules! clip_events_edit {
    (@post_selection keep, $self_:ident) => { $self_.state.selected_event_ids.clone() };
    (@post_selection clear, $self_:ident) => { Vec::new() };
    (@constructor $sequencer:ident) => { ClipEventsEditState::from_sequencer($sequencer) };
    (@constructor $sequencer:ident $ctor:ident) => { ClipEventsEditState::$ctor($sequencer) };
    (
        $name:ident $(, $field:ident : $ftype:ty)*;
        $(constructor = $ctor:ident;)?
        post_selection = $post:ident;
        mutate($self_:ident, $clip:ident) = $mutate:expr
    ) => {
        pub(crate) struct $name {
            state: ClipEventsEditState,
            $($field: $ftype,)*
        }

        impl $name {
            pub(crate) fn from_sequencer(sequencer: &Sequencer $(, $field: $ftype)*) -> Option<Self> {
                Some(Self {
                    state: clip_events_edit!(@constructor sequencer $($ctor)?)?,
                    $($field,)*
                })
            }

            pub(super) fn edit(&mut $self_, sequencer: &mut Sequencer) -> EditResult {
                let post_selection = clip_events_edit!(@post_selection $post, $self_);
                $self_.state.edit_with(sequencer, |$clip| {
                    $mutate;
                    post_selection
                })
            }

            pub(super) fn undo(&mut self, sequencer: &mut Sequencer) -> EditResult {
                self.state.undo(sequencer)
            }
        }
    };
}

clip_events_edit!(
    DeleteSelectedEventsEdit;
    post_selection = clear;
    mutate(self, clip) = clip.delete_selected_events()
);

clip_events_edit!(
    NudgeSelectedEventsEdit, nudge: i32;
    post_selection = keep;
    mutate(self, clip) = clip.nudge_selected_events(self.nudge)
);

clip_events_edit!(
    NudgeSelectedEventsLengthEdit, nudge: i32;
    post_selection = keep;
    mutate(self, clip) = clip.nudge_selected_events_length(self.nudge)
);

clip_events_edit!(
    TransposeSelectedEventsEdit, semitones: i32;
    post_selection = keep;
    mutate(self, clip) = clip.transpose_selected_events(self.semitones)
);

clip_events_edit!(
    MuteSelectedEventsEdit;
    post_selection = keep;
    mutate(self, clip) = clip.toggle_muted_for_selected_events()
);

// `Q`: the selected notes, or the whole clip window with none selected
// (`Clip::quantize`, `070-quantization.md`) — so it accepts an empty
// selection.
clip_events_edit!(
    QuantizeEventsEdit;
    constructor = from_selected_clip;
    post_selection = keep;
    mutate(self, clip) = clip.quantize()
);

#[cfg(test)]
mod tests {

    use crate::models::event::EventType;

    use crate::core::sequencer::test_support::test_sequencer;

    use super::*;

    /// Sets up one selected track/clip with two NoteOn/NoteOff pairs (notes
    /// 60 and 64, velocity 60/40), note 60 selected. Returns the sequencer
    /// plus both NoteOn ids.
    fn sequencer_with_two_notes() -> (Sequencer, Uuid, Uuid) {
        sequencer_with_two_notes_at(0)
    }

    /// `sequencer_with_two_notes`, both notes starting at `on_tick` (100
    /// ticks long).
    fn sequencer_with_two_notes_at(on_tick: i32) -> (Sequencer, Uuid, Uuid) {
        let mut sequencer = test_sequencer();
        let track_id = sequencer.track_id_by_index(0).unwrap();
        sequencer.select_track(Some(track_id));

        let mut clip = Clip::new();
        clip.region_mut().set_region(Some(0), Some(960));
        let clip_id = clip.id();
        clip.add_event(Event::new(on_tick, 0, vec![0x90, 60, 60]));
        clip.add_event(Event::new(on_tick + 100, 0, vec![0x80, 60, 0]));
        clip.add_event(Event::new(on_tick, 0, vec![0x90, 64, 40]));
        clip.add_event(Event::new(on_tick + 100, 0, vec![0x80, 64, 0]));

        let note_60_id = clip
            .events()
            .iter()
            .find(|e| e.note_number() == Some(60) && e.event_type() == Some(EventType::NoteOn))
            .map(|e| e.id())
            .unwrap();
        let note_64_id = clip
            .events()
            .iter()
            .find(|e| e.note_number() == Some(64) && e.event_type() == Some(EventType::NoteOn))
            .map(|e| e.id())
            .unwrap();
        clip.select_event(Some(note_60_id));

        sequencer.tracks_mut()[0].add_clip(&clip);
        sequencer.select_clip(Some(clip_id));

        (sequencer, note_60_id, note_64_id)
    }

    #[test]
    fn drag_events_velocity_edit_targets_explicit_id_not_selection() {
        let (mut sequencer, note_60_id, note_64_id) = sequencer_with_two_notes();

        // Note 60 is selected, but the drag targets note 64 (hovered, unselected).
        let mut edit =
            DragEventsVelocityEdit::from_sequencer(&sequencer, vec![note_64_id], 5, 0).unwrap();
        edit.edit(&mut sequencer);

        let clip = sequencer.selected_clip().unwrap();
        let velocity_of = |id: Uuid| {
            clip.events()
                .iter()
                .find(|e| e.id() == id)
                .unwrap()
                .velocity()
                .unwrap()
        };
        assert_eq!(velocity_of(note_60_id), 60); // untouched
        assert_eq!(velocity_of(note_64_id), 45); // 40 + 5

        edit.undo(&mut sequencer);
        let clip = sequencer.selected_clip().unwrap();
        let velocity_of = |id: Uuid| {
            clip.events()
                .iter()
                .find(|e| e.id() == id)
                .unwrap()
                .velocity()
                .unwrap()
        };
        assert_eq!(velocity_of(note_64_id), 40); // restored
    }

    /// Tick of the NoteOn `id` in the selected clip.
    fn note_on_tick(sequencer: &Sequencer, id: Uuid) -> i32 {
        sequencer
            .selected_clip()
            .unwrap()
            .events()
            .iter()
            .find(|e| e.id() == id)
            .unwrap()
            .tick()
    }

    #[test]
    fn quantize_events_edit_with_a_selection_quantizes_only_it_and_keeps_it() {
        // 100 is off-grid; it quantizes to 129 (the worked example in
        // `quantize.rs`).
        let (mut sequencer, note_60_id, note_64_id) = sequencer_with_two_notes_at(100);

        let mut edit = QuantizeEventsEdit::from_sequencer(&sequencer).unwrap();
        let EditResult::EventsModified {
            selected_event_ids, ..
        } = edit.edit(&mut sequencer)
        else {
            panic!("expected EventsModified");
        };

        assert_eq!(selected_event_ids, vec![note_60_id]);
        assert_eq!(note_on_tick(&sequencer, note_60_id), 129);
        assert_eq!(note_on_tick(&sequencer, note_64_id), 100);

        edit.undo(&mut sequencer);
        assert_eq!(note_on_tick(&sequencer, note_60_id), 100);
    }

    #[test]
    fn quantize_events_edit_without_a_selection_quantizes_the_whole_clip() {
        // 100 is off-grid; it quantizes to 129 (the worked example in
        // `quantize.rs`).
        let (mut sequencer, note_60_id, note_64_id) = sequencer_with_two_notes_at(100);
        sequencer
            .selected_clip_mut()
            .unwrap()
            .clear_event_selection();

        let mut edit = QuantizeEventsEdit::from_sequencer(&sequencer).unwrap();
        let EditResult::EventsModified {
            selected_event_ids, ..
        } = edit.edit(&mut sequencer)
        else {
            panic!("expected EventsModified");
        };

        assert!(selected_event_ids.is_empty());
        assert_eq!(note_on_tick(&sequencer, note_60_id), 129);
        assert_eq!(note_on_tick(&sequencer, note_64_id), 129);

        edit.undo(&mut sequencer);
        assert_eq!(note_on_tick(&sequencer, note_60_id), 100);
        assert_eq!(note_on_tick(&sequencer, note_64_id), 100);
    }

    #[test]
    fn mute_selected_events_from_sequencer_returns_none_when_nothing_selected() {
        let mut sequencer = test_sequencer();
        let track_id = sequencer.track_id_by_index(0).unwrap();
        sequencer.select_track(Some(track_id));

        let mut clip = Clip::new();
        clip.region_mut().set_region(Some(0), Some(960));
        clip.add_event(Event::new(0, 0, vec![0x90, 60, 60]));
        clip.add_event(Event::new(100, 0, vec![0x80, 60, 0]));
        let clip_id = clip.id();
        sequencer.tracks_mut()[0].add_clip(&clip);
        sequencer.select_clip(Some(clip_id));

        assert!(MuteSelectedEventsEdit::from_sequencer(&sequencer).is_none());
    }

    #[test]
    fn mute_selected_events_edit_mutes_the_selected_note() {
        let (mut sequencer, note_60_id, note_64_id) = sequencer_with_two_notes();

        let mut edit = MuteSelectedEventsEdit::from_sequencer(&sequencer).unwrap();
        let EditResult::EventsModified {
            track_idx,
            clip_id,
            selected_event_ids,
            ..
        } = edit.edit(&mut sequencer)
        else {
            panic!("expected EventsModified");
        };
        assert_eq!(track_idx, 0);
        assert_eq!(selected_event_ids, vec![note_60_id]);

        let clip = sequencer.selected_clip().unwrap();
        assert_eq!(clip.id(), clip_id);
        let is_muted = |id: Uuid| {
            clip.events()
                .iter()
                .find(|e| e.id() == id)
                .unwrap()
                .is_muted()
        };
        assert!(is_muted(note_60_id));
        assert!(!is_muted(note_64_id)); // unselected note untouched
    }

    #[test]
    fn mute_selected_events_edit_undo_restores_unmuted_state() {
        let (mut sequencer, note_60_id, _) = sequencer_with_two_notes();

        let mut edit = MuteSelectedEventsEdit::from_sequencer(&sequencer).unwrap();
        edit.edit(&mut sequencer);
        edit.undo(&mut sequencer);

        let clip = sequencer.selected_clip().unwrap();
        assert!(
            !clip
                .events()
                .iter()
                .find(|e| e.id() == note_60_id)
                .unwrap()
                .is_muted()
        );
    }

    #[test]
    fn mute_selected_events_edit_redo_reapplies_the_toggle() {
        let (mut sequencer, note_60_id, _) = sequencer_with_two_notes();

        let mut edit = MuteSelectedEventsEdit::from_sequencer(&sequencer).unwrap();
        edit.edit(&mut sequencer);
        edit.undo(&mut sequencer);
        edit.edit(&mut sequencer);

        let clip = sequencer.selected_clip().unwrap();
        assert!(
            clip.events()
                .iter()
                .find(|e| e.id() == note_60_id)
                .unwrap()
                .is_muted()
        );
    }
}
